Non-Caddy deployment.
chiefonboarding/ChiefOnboarding pull request #206
Opened 2022-08-02 17:29 UTC by megamaiku

Managed to deploy the app without the need for the Caddy extras. Something to note is that I had already created the database using the original script, so I'm didn't thoroughly test the database creation using the proposed non-caddy approach. Hope people find this useful.

2022-08-02 17:40 UTC, GDay requested changes
Thanks a lot for this PR! Apart from these two really small change requests, the changes look good to me and I am happy to merge this.

If you have time, could you please fix those? If not, no worries.

2022-08-02 17:40 UTC, GDay commented on docs/Deployment.md
>  3. Then we need to create a `Caddyfile` to route the requests to the server (change the domain name, obviously):
Nitpicking here, but maybe we can make this `2a` or `2.1`, so we can continue underneath with `3` and keep the ordering correctly?

2022-08-02 17:40 UTC, GDay commented on docs/Deployment.md
> +      - SECRET_KEY=SuperDuperSecretKey
Another nitpick here; for the sake of consistency, can we keep the `SECRET_KEY` the same as the other one? Just to avoid confusion.

2022-08-03 02:19 UTC, megamaiku reviewed
Formatting changes.

2022-08-03 11:33 UTC, GDay commented
Thanks a lot, @megamaiku!

2022-08-03 11:34 UTC, merged