Title: Add OIDC Authentication Support
chiefonboarding/ChiefOnboarding pull request #291
Opened 2023-05-01 14:18 UTC by TaoChan1005

Dear repository maintainers,

I have made some modifications to this repository to support OpenID Connect (OIDC) authentication. My changes involve reading parameters from environment variables, adding new classes and methods to handle OIDC authentication, automatically creating users if they don't exist, and synchronizing user roles every time they log in.

1. Added environment variables to read OIDC configurations:

```python
OIDC_ENABLED = env.bool('OIDC_ENABLED', default=False)
OIDC_CLIENT_ID = env('OIDC_CLIENT_ID', default="")
OIDC_CLIENT_SECRET = env('OIDC_CLIENT_SECRET', default="")
OIDC_AUTHORIZATION_URL = env('OIDC_AUTHORIZATION_URL', default="")
OIDC_TOKEN_URL = env('OIDC_TOKEN_URL', default="")
OIDC_USERINFO_URL = env('OIDC_USERINFO_URL', default="")
OIDC_SCOPES = env('OIDC_SCOPES', default="openid email profile")
OIDC_LOGOUT_URL=env("OIDC_LOGOUT_URL", default="")
OIDC_PERMISSION_ADMIN_PATTEREN = env('OIDC_PERMISSION_ADMIN_PATTEREN', default="^cn=Administrators.*")
OIDC_PERMISSION_MANAGE_PATTEREN = env('OIDC_PERMISSION_MANAGE_PATTEREN', default="^cn=Manage.*")
OIDC_GROUPS_PATH = env('OIDC_GROUPS_PATH', default="zoneinfo").split(",")
OIDC_DEFAULT_ROLE = env.int("OIDC_DEFAULT_ROLE", "3")
OIDC_FORCE_AUTHN=env.bool("OIDC_FORCE_AUTHN", default=False)
OIDC_DEBUG=env.bool("OIDC_DEBUG", default=False)
```

Here's a brief explanation of the purpose of each environment variable:

- **OIDC_ENABLED**: Determines if OIDC authentication is enabled or not (default is False)
- **OIDC_CLIENT_ID**: The OIDC client ID
- **OIDC_CLIENT_SECRET**: The OIDC client secret
- **OIDC_AUTHORIZATION_URL**: The OIDC authorization URL
- **OIDC_TOKEN_URL**: The OIDC token URL
- **OIDC_USERINFO_URL**: The OIDC userinfo URL
- **OIDC_SCOPES**: The OIDC scopes to request (default is "openid email profile")
- **OIDC_LOGOUT_URL**: The OIDC logout URL
- **OIDC_PERMISSION_ADMIN_PATTEREN**: The regex pattern for matching admin group names (default is "^cn=Administrators.*")
- **OIDC_PERMISSION_MANAGE_PATTEREN**: The regex pattern for matching manage group names (default is "^cn=Manage.*")
- **OIDC_GROUPS_PATH**: The path to OIDC groups in the user info (default is "zoneinfo")
- **OIDC_DEFAULT_ROLE**: The default role for users (default is 3)
- **OIDC_FORCE_AUTHN**: Whether to force OIDC authentication (default is False)
- **OIDC_DEBUG**: Whether to enable OIDC debugging (default is False)

2. Added OIDCLoginView class to handle OIDC authentication flow:

- **dispatch**: Ensures OIDC is enabled before handling requests
- **get**: Handles the authorization code and callback or generates the authorization URL for redirection
- **generate_auth_url**: Generates the authorization URL for the OIDC provider
- **handle_callback**: Handles the OIDC callback, exchanging authorization code for tokens, and authenticating the user
- **request_tokens**: Requests tokens from the OIDC provider using the authorization code
- **get_user_info**: Retrieves user information using the access token
- **authenticate_user**: Authenticates the user based on the retrieved user information
- Other internal methods for managing user synchronization, permissions, and configuration

add endpoint 
```python
path("api/auth/oidc_login/", views.OIDCLoginView.as_view(), name="oidc_login"),
```

3. Added NewLogoutView class to handle OIDC logout:

- **dispatch**: Redirects to the OIDC logout URL if OIDC is enabled

With these changes, this repository now supports OIDC authentication. Please review my pull request and let me know if you have any questions or need further clarification.

Thank you for your consideration.

Best regards,

2023-05-01 22:17 UTC, GDay requested changes
Thanks for this PR, this looks good! I made a few comments here, if anything seems to be too hard or too much work, then let me know and I will give you more tips on how to do it or I will fix it myself (what you want).

Also, we have this setting in the `organization` model that allows users to select what options they want to see this: 
https://github.com/chiefonboarding/ChiefOnboarding/blob/a523aa0da60fb53b588517c9846e046ad38170e3/back/organization/models.py#L54-L64

Could you add OIDC there too? I think that would be better to keep things more centralized. It might even be good to remove the `OIDC_ENABLED` setting and just rely on that new database field to determine if the endpoint should be blocked and if a button should be shown on the login page.

2023-05-02 10:16 UTC, TaoChan1005 commented
I have done these

2023-05-02 15:20 UTC, GDay requested changes
Thanks for going through the requested changes. I have a few more - we are getting very close to merging this!

Again, if anything seems to be too hard or too much work, then let me know!

2023-05-02 15:20 UTC, GDay commented on back/user_auth/views.py
> +    def __init_config(self):
I think we can remove this function? Doesn't seem to be used anymore.

2023-05-02 15:20 UTC, GDay commented on back/user_auth/views.py
> +        # print(tmp)
Please remove all commented out code that is not relevant, like this one.

2023-05-02 15:20 UTC, GDay commented on back/admin/settings/forms.py
> +            oidc_login = self.cleaned_data["oidc_login"]
Nitpicking here a bit, but maybe just change this with: 
```
oidc_login = self.cleaned_data.get("oidc_login", False)
```

That will try to get it, if it doesn't exist, it will default to `False`.

2023-05-02 15:20 UTC, GDay commented on docs/Deployment.md
> +This will create new migrations based on the changes you made to your models and apply them to the database.
Could you remove this and include the migration file? Migration files should be commited to the repository.

The docker file and any of the PaaS solutions will automatically migrate all migrations, so that's all good, no need to specify that here.

2023-05-02 15:20 UTC, GDay commented on back/admin/integrations/models.py
> +                # return False
Is there are reason why you commented this out?

2023-05-02 17:35 UTC, TaoChan1005 commented on back/admin/integrations/models.py
> +                # return False
When I execute multi jobs, if one failed, the remained tasks would be executed.

2023-05-02 17:41 UTC, TaoChan1005 commented
I think I have doned it.but  i didn't edit test.py

2023-05-05 02:28 UTC, GDay commented
The tests were failing because it checks every url on authentication. I have added the new url (which doesn't have authentication) to the whitelist, so that passes. There was one other test that failed because you had changed allowed it to continue after a failed request in the sequences, I reverted that change, so the comment on that.

I have also ran black/flake8/isort since you probably forgot to run that.

I still need to test this on my staging environment, but overall this looks good. If testing works, then I will merge this.

2023-05-06 00:32 UTC, TaoChan1005 commented
I'm unable to run tests on my computer and I'm encountering issues with the `test.py` file when trying to test `oidc_login`. I'm not sure how to fix these problems.


I have made several modifications to the `view.py` file. A new endpoint `/login` has been added, called `PureAuthenticateView`, which retains the previous login functionality. This is useful because an environment variable `OIDC_FORCE_AUTH` has been introduced, which, when set, always redirects the main page to OIDC for authentication. However, users can still access the manual login page via https://xxxx.com/login if they don't want to use OIDC authentication.

Additionally, I've set the `OIDC_FORCE_AUTH` value to `session['force_auth']`. This ensures that if something goes wrong with OIDC authentication, the user will be redirected to the `/login` page. This behavior is particularly helpful when `OIDC_FORCE_AUTH` is set to true.

2023-05-12 01:18 UTC, GDay commented
@TaoChan1005 I have just made a few changes, I have also fixed the tests. 

Most notable:
1. I have removed the extra login view, so we can just have one login form. We can force it to render normally by adding `?disable_force=true` to the url. 
2. I have added a new hire role. When it was syncing the roles, there was no role for the new hire. So, if the new hire would log in, they would get the "other" role instead of the new hire role they should have.
3. I have added the option to disable syncing roles. I have been testing with auth0 and it seems like they don't support a `zoneinfo` option or something similar to get the roles with OIDC. I am not sure how common that is.

It seems to be working well on my test server, so that's great!

If you have time, please take a look at the changes I made and let me know if that looks okay to you. This is the first time I working with OIDC, so I don't know all the ins and outs of it. 

Thanks!

2023-05-12 01:21 UTC, GDay commented on back/admin/integrations/models.py
> +                # return False
I have reverted this as it makes the tests fail. Currently, it's intended behavior that it stops when one of the requests fail. Let's say we have an integration where we create a new user in a application and then update some of their settings. If the creation would fail, then we shouldn't try to update their settings as the user wouldn't even exist.

Though, I would be open to a PR that would allow us to set an option in the JSON integration manifest to configure this behavior.

2023-06-13 15:54 UTC, GDay commented
@TaoChan1005 this looks good to me know. I have added a few more fixes:
- Let the OIDC provider return back to the normal Django logout, so the user's Django session becomes invalid
- Set an 'unusable password' to the user if they have been created through OIDC, so they can only login through OIDC.
- Rebased everything and merged the migrations
- Added logging for when something goes wrong at the OIDC.
- Changed splitting on `comma` to `dot`, as that's the default throughout the project.

2023-06-13 19:53 UTC, GDay approved these changes

2023-06-13 19:54 UTC, merged

2023-06-13 20:14 UTC, GDay commented
Just merged it. Thanks a lot for creating the PR!

2023-06-19 12:44 UTC, vakninr commented
In which version this feature is planned to be released? Thanks

2023-06-19 13:36 UTC, GDay commented
@vakninr I have just released a new docker build