Add access as context variable
chiefonboarding/ChiefOnboarding pull request #385
Opened 2023-11-01 01:34 UTC by GDay

This will allow users to add the current access status of all integrations in any of the content boxes or integrations.

2023-11-01 01:37 UTC, GDay commented on back/users/models.py
> +        if "{{ access_overview }}" in text:
I honestly don't like this hack. Adding this directly to the dictionary will cause a lot of lookups for no reason. Though, I feel like this is the easiest solution, but I am open to suggestions.
Alternative solution would be to heavily cache the variable, but I have refrained from doing this as it would be unclear when to invalidate cache - which could result in incorrect data.

2023-11-04 22:01 UTC, cscheng requested changes

2023-11-04 22:01 UTC, cscheng commented on back/users/models.py
> +                    access_str = "(unknown)"
Shouldn't `access_str` be translatable?

2023-11-05 01:25 UTC, GDay commented on back/users/models.py
> +        if "{{ access_overview }}" in text:
Good suggestion! This would have been dope, but it doesn't seem to work (I have updated my code), unfortunately. I have nothing to back this up, but I think that `Template(text).render()` forces all values to be rendered, regardless if they are called lazy.

With the current code in place, when I try to get a new hire to do item (from their dashboard), it will be stuck in an infinite loop. Full error here as the test fails: https://github.com/chiefonboarding/ChiefOnboarding/actions/runs/6758278461/job/18369745732. The template calls a template tag (`personalize`), which then checks all integrations and every integration will call the `personalize` method to replace values from the manifest. I could remove the `access_overview` for when we are rendering it through the template tag, but that doesn't solve this issue for other parts of the system (emails, text messages, integrations etc).

Any other ideas? As a last resort, I might just need to push the whole user object through the context, but I don't really want to to do that as I wouldn't really have much control over what would be used by users which could lead to unexpected errors.

2023-11-05 09:25 UTC, cscheng commented on back/users/models.py
> +        if "{{ access_overview }}" in text:
My bad, `keep_lazy_text` cannot be used as when you don't pass arguments to the function, it will immediately call the function that is decorated (I haven't used it on functions without arguments before). What does work is if you define this `"access_overview": lazy(self.get_access_overview, str)` in `new_hire_context`.

That being said, while `keep_lazy_text` didn't work, it did expose an issue with the `check_integration_access()` method. There is a recursion error, due to `.user_exists()` calling `._replace_vars()`, which in turn calls `.personalize()`, which will call `.user_exists()` again etc. This is not noticeable in `test_personalize` because `.user_exists()` is patched. So this still needs to be addressed.

2023-11-07 01:39 UTC, GDay commented on back/users/models.py
> +        if "{{ access_overview }}" in text:
Thanks, that worked! I have created a separate issue to deal with that recursion issue later so I can merge this PR. It's extremely unlikely to ever be triggered as `access_overview` doesn't really have a use in the `exists` part of the manifest, so it's not a big deal right now.

2023-11-07 01:40 UTC, merged