Add complete and reopen admin task functionality from People/new hire view
chiefonboarding/ChiefOnboarding pull request #404
Opened 2023-11-16 20:46 UTC by JonasMe

Added "Action" header to "Admin task" table in "new hire -> Admin task" view.
![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/3063806/f47d6a61-2792-4997-b70c-05b4034193cb)

Upon clicking the task will either be completed or reopened and appropiate message displayed.

![image](https://github.com/chiefonboarding/ChiefOnboarding/assets/3063806/7e30d359-f2b7-4d15-8043-dcd7cb870521)

2023-11-16 22:44 UTC, GDay reviewed
Thanks for the PR @JonasMe! I like the feature of allowing users to mark admin tasks from the overview view instead of having to go into the admin task to make it as completed.

I have my doubts about the reopening of tasks. As you saw, the admin tasks trigger other conditions from a sequence. The issue here is that not all of these triggers are logged/saved. Some of these (like the integration items) run and are not assigned to a user in any easy to lookup way, which means that completing the same admin task again would rerun that integration, which is likely not the expected behavior. So I would prefer to not allow the reopening of tasks at the moment.

2023-11-17 07:28 UTC, JonasMe commented
Hi @GDay  - Thanks for the feedback. I can see the sense in removing the "reopening" until perhaps there is a lookup-table of executed tasks to prevent rerunning.

I'll remove that option as well as fixing the tests asap.

2023-11-17 07:30 UTC, JonasMe commented on back/admin/people/new_hire_views.py
> +class CompleteAdminTaskView(
Thanks for the feedback @GDay 

I've seen that view but i guess i'm still figuring the conventions revolving the repo.

How would you prefer i reuse the view, while at the same time making sure the redirect goes to the right page (and not the admin task detail page)?

Thanks a bunch

2023-11-17 23:59 UTC, GDay commented on back/admin/people/new_hire_views.py
> +class CompleteAdminTaskView(
Ah, that's right. I forgot about the redirect. I think this is fine for now. Thanks!

2023-11-18 00:00 UTC, GDay requested changes
Two small things that would be nice to address and then this looks good to merge. Thanks!

2023-11-18 00:00 UTC, GDay commented on back/admin/people/templates/_unmark_complete_icon.html
> + <svg xmlns="http://www.w3.org/2000/svg" style="margin: 0 -0.25rem 0 -.25rem" class="icon icon-tabler icon-tabler-discount-off" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="cur
I think we can remove this file as well now since the removing feature has been removed.

2023-11-18 12:43 UTC, GDay approved these changes
LGTM! Thanks!

2023-11-18 12:59 UTC, JonasMe commented
> LGTM! Thanks!

Great to hear @GDay  - a whitespace was missing in the auth files which Black dident like. I've reformatted and all should be good to go.

2023-11-18 16:44 UTC, GDay approved these changes

2023-11-18 16:45 UTC, merged